config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pokemons#index"
  resources :pokemons
  resources :users

  get 'login', to: 'sessions#new', as: 'login'

  post 'sessions', to: 'sessions#create'

  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :user, optional: true
  
  def self.search(search)
    if search
      where(["name LIKE?","%#{search}%"])
    else
      all
    end
  end
  def self.per_page
    9
  end
end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Validations
  has_secure_password

  # has_many :pokemon :foreign_key => "pokemon_type"

  validates :name, presence: true, uniqueness: true, length: {minimum: 1, maximum:20}
  validates :email, presence: true, uniqueness: true, length: {minimum: 1}
  validates :password, presence: true, length: {minimum: 6}

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    @pokemons = Pokemon.search(params[:search])
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
  if current_user.nil?
    @user = User.new
  else
    redirect_to user_path(current_user)
  end
end

  def create
    @user = User.confirm(login_params)
      if @user
        login(@user)
        flash[:notice] = "Successfully logged in."
        redirect_to @user
      else
        flash[:error] = "Incorrect email or password"
        redirect_to login_path
    end
end

  def destroy
    logout
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end
end

private

  def login_params
    params.require(:user).permit(:email, :password)
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create, :user_params, :show]
  before_action :check_owner, only: [:edit, :update, :destroy]


  def index
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:success] = "Account Successfully Created!"
      login @user
        redirect_to @user
    else
      flash[:error] = @user.errors.full_messages.join(". ")
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update

    @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:success] = "Profile Updated!"
        redirect_to user_path(@user)
      else
        flash[:error] = "Profile was not updated! Please try again!"
        render :edit
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
      flash[:success] = "User has been successfully deleted!"
      redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password ,:profile_image)
  end

  def check_owner
    if session[:user_id] != User.find(params[:id]).id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def login(user)
  session[:user_id] = user.id
  @current_user = user
end

def current_user
  @current_user ||= User.find_by_id(session[:user_id])
end

def logout
  @current_user = session[:user_id] = nil
end

def require_login
  if session[:user_id].nil?
    flash[:error] = "Please sign in or create an account to access this domain!"
  redirect_to new_user_path
  end
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sign_in.html.erb
<h4>Sign-in</h4>
<div class="sign_in_div">
  Email<%= f.email_field :email, placeholder:"Email"%>
</div>
<div class="sign_in_div">
  Password<%= f.password_field :password, placeholder:"Password", id:'sign_in_form'%>
</div>

app/views/layouts/_user_forms.html.erb
<h5>Become a Pokemon Master Today!</h5>
  <div>
    <%= f.label :name, "Name"%>
    <%= f.text_field :name%>
  </div>
  <div>
    <%= f.label :email, "Email"%>
    <%= f.email_field :email%>
  </div>
  <div>
    <%= f.label :password, "Password"%>
    <%= f.password_field :password%>
  </div>
  <div>
    <%= f.label :profile_image, "Profile Image"%>
    <%= f.url_field :profile_image%>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokédex</title>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="navbar-fixed">

  <nav>
      <div class="nav-wrapper">
      <%= link_to root_path do %>
      <%= image_tag(asset_path("logov2.svg"), class:"brand-logo", style: "height: 100%") %>
      <% end %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <% if current_user %>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Log Out", logout_path %></li>
        <% else %>
        <li><%= link_to "Register", href="#sign-up", class:"modal-trigger"%></li>
        <li><%= link_to "Sign in", href="#sign-in-modal", class:"modal-trigger"%></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

<ul class="side-nav" id="mobile-demo">
  <% if current_user %>
  <li><%= link_to "Profile", user_path(current_user) %></li>
  <li><%= link_to "Log Out", logout_path %></li>
  <% else %>
  <li><%= link_to "Register", new_user_path %></li>
  <li><%= link_to "Sign in", login_path %></li>
  <% end %>
</ul>

<!-- MODAL FOR SIGNUP -->
  <div class="modal-for-sign-up">
    <%= form_for (User.new), url:users_path, method: "post" do |f| %>
    <div id="sign-up" class="modal">
      <div class="modal-content">

        <%= render partial: "layouts/user_forms", locals: { f: f } %>
      </div>
      <div class="modal-footer">
        <%= f.submit "Create Account", class: "modal-action modal-close waves-effect red waves-red btn-large" %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- MODAL FOR LOGIN -->
  <div class="modal-for-sign-in">
  <%= form_for :user, url: "/sessions", method: "post" do |f| %>
  <div id="sign-in-modal" class="modal">
    <div class="modal-content">
      <%= render partial: "layouts/sign_in", locals: { f: f } %>
    </div>
    <div class="modal-footer">
      <%= f.submit "LOG IN", class: "modal-action modal-close waves-effect red btn-large", id: "sign-in-button" %>
      <% end %>
    </div>
  </div>
</div>
  <!--Flashing messages on pages  -->
  <div class="col s8 push-s2">
    <% flash.each do |name, msg| %>
    <div id='toast-container'>
      <%= javascript_tag "Materialize.toast('#{msg}', 4000)" %>
    </div>
    <% end %>
  </div>
  <%= yield %>
</body>
</html>

app/views/pokemons/index.html.erb
<body>

<h1><a href="https://fontmeme.com/pokemon-font/">
    <img src="https://fontmeme.com/permalink/171102/67992abef63bbc6a2025b2e69bd481b3.png"
    alt="pokemon-font" border="0"></a></h1>

<div class="search-field">
<section>
  <h5>Search for Pokémon: </h5>
    <%= form_tag pokemons_path, :method => 'get' do%>
    <%= text_field_tag :search, params[:search] ,placeholder:"Pokémon Name" %>
    <%= submit_tag "Search"%>
  <% end %>
</section>
</div>


<% @pokemons.each do |pokemon| %>
<!-- Modal Trigger -->

<a class="waves-effect waves-light btn modal-trigger" href="#modal1-<%=pokemon.pokemon_id%>">
  <ul>
    <li>
      <%= image_tag pokemon.image, :class => "pokemon" %>
    </li>
    <li>
      <%= pokemon.name%>
    </li>
  </ul>
</a>
<!-- Modal Structure -->
<div id="modal1-<%=pokemon.pokemon_id%>" class="modal">

  <div class="modal-content">
    <div class="id"><%= pokemon.pokemon_id%></div>
    <div class="name"><%= pokemon.name %></div>
    <div class="species"><%= pokemon.species %></div>
    <div class="type"><%= pokemon.pokemon_type %></div>
    <div class="height"><%= pokemon.height %></div>
    <div class="weight"><%= pokemon.weight %></div>
    <div class="description"><%= pokemon.description %></div>
    <div class="gif"><%= image_tag pokemon.gif, class:"poke-gif"%></div>
    <div class="footprints"><%= image_tag pokemon.footprint , class:"poke-footprints"%></div>
  </div>
</div>
<%end%>

</body>

app/views/users/edit.html.erb
<div class="container">
  <div class="row" style="margin-top: 0.75rem">
      <h3>Editing Profile for <%=@user.name %></h3>
      <%= form_for @user do |f| %>
      <div>
        <%= f.label :name%>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.label :email%>
        <%= f.email_field :email %>
      </div>
      <div>
        <%= f.label :password%>
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :profile_image%>
        <%= f.url_field :profile_image %>
      </div>
      <div class="btn-inline">
      <%= f.submit "Save Changes", class: "btn" %>
      <% end %>
     </div>

app/views/users/new.html.erb
<legend>Become A Pokemon Master!</legend>

<%= form_for @user do |f| %>
  <div>
    Name:<%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    Email:<%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    Password:<%= f.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    Profile Image:<%= f.url_field :profile_image, placeholder: "Insert link for Profile Image" %>
  </div>
  <%= f.submit "Sign Up", class: "btn" %>
<% end %>

app/views/users/show.html.erb
<!-- BEGIN Profile image and description -->
<!-- BEGIN Profile IMAGE -->
<body class="user-show">
  <div class="prof-image">
    <% if @user.profile_image.empty? %>
    <%= image_tag(asset_path('default_user_no_image.jpeg'), class: "circle") %>
    <% else %>
    <%= image_tag(@user.profile_image, class: "circle") %>
    <% end %>
  </div>
  <div class="container">
    <div class="row" style="margin-bottom: 0px">
      <div class="col s12 wht-cont z-depth-5">
        <!-- BEGIN PROFILE INFO -->
        <div class="prof-description">
          <h4><%= @user.name.capitalize %></h4>
          <b>Date Joined: </b><%= @user.created_at.strftime("%B").to_s + " " + @user.created_at.year.to_s %></p>
          <%= link_to user_path(@user),
                data: {title: 'Permanently delete',
                confirm: "Are you sure? This action cannot be undone."},
                class: 'modal-action modal-close waves-effect red btn-large',
                method: :delete  do %>
                DELETE USER
          <% end %>
          <%= link_to "Edit Profile", edit_user_path(current_user),
                class: "modal-action modal-close waves-effect red btn-large" %>
          <h5>Pokemon Caught:</h5>
        </div>
</body>